# Config file for Travis CI
dist: xenial
language: python
python: 3.7.6
install:
  - pip install -r requirements_dev.txt
  - pip install -e .

script:
  - pytest -v --cov=termostabilizator

after_success: # This is for DeepSource.io
  # Generate coverage report in xml format
  - coverage xml

  # Install deepsource CLI
  - curl https://deepsource.io/cli | sh

  # From the root directory, run the report coverage command
  - ./bin/deepsource report --analyzer test-coverage --key python --value-file ./coverage.xml
